/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Info: typeof import('./src/components/info.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInfo: typeof import('./src/components/TheInfo.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheProjectView: typeof import('./src/components/TheProjectView.vue')['default']
    TheTechnology: typeof import('./src/components/TheTechnology.vue')['default']
  }
}
